name: Fable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Restore tools
      run: dotnet tool restore
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run Fable tests
      run: dotnet fable Fuchu.FableTests --outDir bin --runScript ./bin /d
